# Generated by Django 2.0.10 on 2019-02-04 21:27

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import dof_conf.utils.storage
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduleItem',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('datetime', models.DateTimeField(verbose_name='date and time')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this item should be treated as active. Unselect this instead of deleting schedule items.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'schedule item',
                'verbose_name_plural': 'schedule items',
                'ordering': ('-datetime',),
            },
        ),
        migrations.CreateModel(
            name='Speaker',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='name')),
                ('about', models.TextField(blank=True, verbose_name='about')),
                ('github', models.URLField(blank=True, verbose_name='GitHub')),
                ('facebook', models.URLField(blank=True, verbose_name='Facebook')),
                ('twitter', models.URLField(blank=True, verbose_name='Twitter')),
                ('linkedin', models.URLField(blank=True, verbose_name='LinkedIn')),
                ('photo', models.ImageField(blank=True, upload_to=dof_conf.utils.storage.upload_to, verbose_name='photo')),
                ('position', models.PositiveIntegerField(default=1, help_text='Determines at which position this speaker is displayed on the website.', verbose_name='position')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this speaker should be treated as active or not. Unselect this instead of deleting speakers.', verbose_name='active')),
            ],
            options={
                'verbose_name': 'speaker',
                'verbose_name_plural': 'speakers',
                'ordering': ('position',),
            },
        ),
        migrations.AddField(
            model_name='scheduleitem',
            name='speaker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appearances', to='conference.Speaker', verbose_name='speaker'),
        ),
    ]
