# Generated by Django 2.0.10 on 2019-03-01 20:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('conference', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scheduleitem',
            options={'ordering': ('datetime',), 'verbose_name': 'schedule item', 'verbose_name_plural': 'schedule items'},
        ),
    ]
