# Generated by Django 2.0.10 on 2019-02-14 20:54

from django.db import migrations, models
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('email', models.CharField(max_length=254, unique=True, verbose_name='email address')),
                ('number_of_tees', models.PositiveSmallIntegerField(default=1, help_text='The number of T-Shirts we should save for you.', verbose_name='number of tees')),
                ('number_of_stickers', models.PositiveSmallIntegerField(default=1, help_text='The number of stickers we should save for you.', verbose_name='number of stickers')),
                ('subscribed', models.BooleanField(default=True, help_text='Designates whether the person has subscribed to news about the event.', verbose_name='subscribed')),
            ],
            options={
                'verbose_name': 'reservation',
                'verbose_name_plural': 'reservations',
                'ordering': ('created',),
            },
        ),
    ]
